---
title: Modelling
author: Matthew Gordon
date: today
format: 
  html: 
    self-contained: true
    df-print: tibble
editor_options: 
  chunk_output_type: console
execute: 
  warning: false
  message: false
  echo: false
---

```{r, setup}
pacman::p_load(ggplot2, tidyverse, tidymodels, readr, here)

data <- read_csv(here("data", "clean_data.csv"))

glimpse(data)
```

# Cleaning #

```{r}
snp_cols <- data |> 
  select(starts_with("rs")) |> 
  colnames()

data <- data |> 
  mutate(
    treatment = as.factor(treatment),
    sex = as.factor(sex),
    across(all_of(snp_cols), as.factor),     
    PR = as.factor(PR)        # PR is binary → classification problem
  )

glimpse(data)
```

# Splitting #

```{r}
set.seed(123)

# Why: split data to evaluate model on unseen data
split_AF <- initial_split(data, strata = treatment)

train_AF <- training(split_AF)
test_AF  <- testing(split_AF)
```

```{r}
cv_AF <- vfold_cv(train_AF)
cv_AF
```

# Workflow #

```{r}
recipe_AF <- recipe(AF ~ treatment + age + sex + ., data = train_AF) |>
  step_rm(PR) |>
  step_zv(all_predictors()) |>
  step_impute_mode(all_nominal_predictors()) |>
  step_impute_mean(all_numeric_predictors()) |>
  step_dummy(all_nominal_predictors()) |>  
  step_normalize(all_numeric_predictors())

model_AF <- linear_reg(
  penalty = tune(),
  mixture = 1   # LASSO
) |> 
  set_engine("glmnet")

wf_AF <- workflow(recipe_AF, model_AF)
```

# Tune Model #

```{r}
doParallel::registerDoParallel()

AF_grid <- grid_regular(penalty(),  levels = 50)

tuned_AF <- tune_grid(
  wf_AF,
  resamples = cv_AF,
  grid = AF_grid
)
```

# Choose Model #

```{r}
collect_metrics(tuned_AF)
autoplot(tuned_AF)

show_best(tuned_AF, metric = "rmse")

penalty <- select_best(tuned_AF, metric = "rmse")
penalty
```

```{r}
wf_AF <- wf_AF |> 
  finalize_workflow(penalty)
wf_AF
```

# Fit Final Model #

```{r}
fit_AF <- wf_AF |> 
  fit(train_AF)

fit_AF

fit_AF |> 
  extract_fit_parsnip() |> 
  vip::vi() |> 
  filter(Importance > 0) |>   # keep non-zero (selected by LASSO)
  mutate(
    Variable = fct_reorder(Variable, Importance)
  ) |> 
  ggplot(aes(Importance, Variable)) + 
  geom_col() +
  labs(
    title = "Variable Importance (LASSO Selected Predictors)",
    x = "Importance",
    y = "Predictor"
  )
```

# Last Fit #

```{r}
last_fit(wf_AF, split_AF) |> 
  collect_metrics()
```


